# Generated by Django 5.0.3 on 2024-03-07 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('backspace_count', models.IntegerField(default=0)),
                ('letter_click_counts', models.JSONField(default=dict)),
                ('typing_duration', models.IntegerField()),
                ('question_presented_at', models.DateTimeField(blank=True, null=True)),
                ('answer_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_interaction_time', models.IntegerField(blank=True, null=True)),
                ('response_type', models.CharField(choices=[('PERSONAL', 'Personal Answer'), ('AI_PARAPHRASE', 'AI Paraphrased'), ('FULLY_AI', 'Fully AI')], max_length=15)),
                ('device_type', models.CharField(choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
    ]
