# Generated by Django 5.0.3 on 2024-03-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='device_type',
            field=models.CharField(blank=True, choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_type',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'Personal Answer'), ('AI_PARAPHRASE', 'AI Paraphrased'), ('FULLY_AI', 'Fully AI')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='typing_duration',
            field=models.IntegerField(default=0),
        ),
    ]
