# Generated by Django 5.0.3 on 2024-03-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_response_answer_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='UserResponse',
        ),
    ]
