# Generated by Django 5.0.3 on 2024-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userresponse_session_delete_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='answer_submitted_at',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question_presented_at',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='total_interaction_time',
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
